modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
    modId="bundled_up"
    version="1.18.2-1.0.1"
    displayName="Bundled Up"
    logoFile="icon.png"
    authors="jerrylu086"
    description="Makes the bundles obtainable and appear in your creative inventory!"
    itemIcon="minecraft:bundle"

[[dependencies.bundled_up]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bundled_up]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"