modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"

[[mods]]
    modId="bundled_up"
    version="1.19.2-1.0.1"
    displayName="Bundled Up"
    logoFile="icon.png"
    authors="jerrylu086"
    description="Makes the bundles obtainable and appear in your creative inventory!"
    itemIcon="minecraft:bundle"

[[dependencies.bundled_up]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bundled_up]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"